server:
  port: 667

logging:
  level:
    xyz:
      dingxs:
        subscribeclient: debug
  file:
    path: logs/subscribe-client.log

api-config:
  apis:
    GetSniffResApi: http://localhost:666/sniff/getSniffRes
    UpdatePortApi: http://localhost:666/subscribe/updatePort

authorized:
  token: 7a9f0305db436ed82a0c91f270fd5685

v2ray:
  fileName: config.json
  restartShell: systemctl restart v2ray
  statusShell: systemctl status v2ray

clint-ask:
  cron: 0/10 * * * * ?