server:
  port: 667

logging:
  level:
    xyz:
      dingxs:
        subscribeclient: debug
  file:
    path: logs
    name: logs/subscribe-client.log

subscribe-client-config:
  apisConfig:
    apis:
      GetSniffResApi: http://localhost:666/sniff/getSniffRes
      UpdatePortApi: http://localhost:666/subscribe/updatePort
      GenerateNewPortApi: http://localhost:666/sniff/generateNewPort
  authorized:
    token: 7a9f0305db436ed82a0c91f270fd5685
  v2ray:
    fileName: config.json
    restartShell: systemctl restart v2ray
    statusShell: systemctl status v2ray
  cron: 0/10 * * * * ?